//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RookiesInTraining2.Pages.student
{
    public partial class join_class
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.TextBox txtClassCode;
        protected global::System.Web.UI.WebControls.Button btnJoinClass;
        protected global::System.Web.UI.WebControls.HyperLink lnkCancel;
    }
}

