//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RookiesInTraining2.Pages.student
{
    public partial class student_class
    {
        protected global::System.Web.UI.WebControls.Label lblClassName;
        protected global::System.Web.UI.WebControls.Label lblClassCode;
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
        protected global::System.Web.UI.WebControls.HiddenField hfClassSlug;
        protected global::System.Web.UI.WebControls.HiddenField hfLevelsJson;
        protected global::System.Web.UI.WebControls.HiddenField hfForumPostsJson;
        protected global::System.Web.UI.WebControls.HiddenField hfProgressJson;
    }
}

