//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RookiesInTraining2.Pages.student
{
    public partial class take_level
    {
        protected global::System.Web.UI.WebControls.Label lblLevelTitle;
        protected global::System.Web.UI.WebControls.Label lblDescription;
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
        protected global::System.Web.UI.WebControls.Label lblQuizTitle;
        protected global::System.Web.UI.WebControls.Label lblTimeLimit;
        protected global::System.Web.UI.WebControls.Label lblPassingScore;
        protected global::System.Web.UI.WebControls.HyperLink lnkTakeQuiz;
        protected global::System.Web.UI.WebControls.HiddenField hfSlidesJson;
        protected global::System.Web.UI.WebControls.HiddenField hfLevelSlug;
        protected global::System.Web.UI.WebControls.HiddenField hfClassSlug;
    }
}

