//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RookiesInTraining2.Pages.admin
{


    public partial class ActivityLog
    {

        /// <summary>
        /// ddlActionType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlActionType;

        /// <summary>
        /// txtAdminSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAdminSearch;

        /// <summary>
        /// txtStartDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;

        /// <summary>
        /// txtEndDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEndDate;

        /// <summary>
        /// btnApplyFilters control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnApplyFilters;

        /// <summary>
        /// lblLogCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblLogCount;

        /// <summary>
        /// gvActivityLogs control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvActivityLogs;

        /// <summary>
        /// lblNoLogs control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoLogs;

        /// <summary>
        /// lblPageError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPageError;

        /// <summary>
        /// lblPageMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPageMessage;
    }
}

