//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RookiesInTraining2.Pages.admin
{
    public partial class add_students
    {
        protected global::System.Web.UI.WebControls.Label lblClassName;
        protected global::System.Web.UI.WebControls.Label lblClassCode;
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Label lblAvailableCount;
        protected global::System.Web.UI.WebControls.Repeater rptAvailableStudents;
        protected global::System.Web.UI.WebControls.Label lblNoAvailable;
        protected global::System.Web.UI.WebControls.Label lblEnrolledCount;
        protected global::System.Web.UI.WebControls.Repeater rptEnrolledStudents;
        protected global::System.Web.UI.WebControls.Label lblNoEnrolled;
    }
}




