//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RookiesInTraining2.Pages.admin
{
    public partial class create_quiz
    {
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.DropDownList ddlLevelForQuiz;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLevel;
        protected global::System.Web.UI.WebControls.TextBox txtQuizTitle;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvQuizTitle;
        protected global::System.Web.UI.WebControls.TextBox txtTimeLimit;
        protected global::System.Web.UI.WebControls.TextBox txtPassingScore;
        protected global::System.Web.UI.WebControls.DropDownList ddlQuizMode;
        protected global::System.Web.UI.WebControls.CheckBox chkPublishQuiz;
        protected global::System.Web.UI.WebControls.HiddenField hfClassSlug;
        protected global::System.Web.UI.WebControls.HyperLink lnkCancel;
        protected global::System.Web.UI.WebControls.Button btnCreateQuiz;
    }
}


