//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RookiesInTraining2.Pages.admin
{
    public partial class manage_slides
    {
        protected global::System.Web.UI.WebControls.Label lblLevelTitle;
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Repeater rptSlides;
        protected global::System.Web.UI.WebControls.Label lblNoSlides;
        protected global::System.Web.UI.WebControls.Label lblSlideError;
        protected global::System.Web.UI.WebControls.HiddenField hfSlideNumber;
        protected global::System.Web.UI.WebControls.DropDownList ddlContentType;
        protected global::System.Web.UI.WebControls.TextBox txtContent;
        protected global::System.Web.UI.WebControls.FileUpload fileUploadImage;
        protected global::System.Web.UI.WebControls.TextBox txtMediaUrl;
        protected global::System.Web.UI.WebControls.HiddenField hfLevelSlug;
        protected global::System.Web.UI.WebControls.HiddenField hfClassSlug;
        protected global::System.Web.UI.WebControls.HiddenField hfEditingSlideNumber;
        protected global::System.Web.UI.WebControls.Button btnSaveSlide;
    }
}


