//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RookiesInTraining2.Pages
{


    public partial class AdminReports
    {

        /// <summary>
        /// btnPrint control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPrint;

        /// <summary>
        /// btnExportCsv control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnExportCsv;

        /// <summary>
        /// txtStartDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;

        /// <summary>
        /// txtEndDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEndDate;

        /// <summary>
        /// ddlRoleFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRoleFilter;

        /// <summary>
        /// btnApplyFilters control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnApplyFilters;

        /// <summary>
        /// lblTotalUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalUsers;

        /// <summary>
        /// lblNewUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNewUsers;

        /// <summary>
        /// lblTeacherCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTeacherCount;

        /// <summary>
        /// lblAverageDaily control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAverageDaily;

        /// <summary>
        /// rptRoleBreakdown control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptRoleBreakdown;

        /// <summary>
        /// lblResultCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblResultCount;

        /// <summary>
        /// gvReport control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvReport;

        /// <summary>
        /// lblNoResults control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoResults;

        /// <summary>
        /// rptRecentRegistrations control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptRecentRegistrations;

        /// <summary>
        /// lblNoRecent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoRecent;

        /// <summary>
        /// lblPageError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPageError;

        /// <summary>
        /// lblPageMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPageMessage;
    }
}


