//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RookiesInTraining2.Pages
{


    public partial class AdminReports
    {

        /// <summary>
        /// btnExportCsv control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnExportCsv;

        /// <summary>
        /// btnPrint control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPrint;

        /// <summary>
        /// lblTotalStudents control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalStudents;

        /// <summary>
        /// lblActiveStudents control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblActiveStudents;

        /// <summary>
        /// lblTotalTeachers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalTeachers;

        /// <summary>
        /// lblActiveTeachers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblActiveTeachers;

        /// <summary>
        /// lblTotalClasses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalClasses;

        /// <summary>
        /// lblActiveClasses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblActiveClasses;

        /// <summary>
        /// ddlTimePeriod control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlTimePeriod;

        /// <summary>
        /// txtStartDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;

        /// <summary>
        /// txtEndDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEndDate;

        /// <summary>
        /// txtSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>
        /// ddlStatusFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;

        /// <summary>
        /// btnApplyFilters control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnApplyFilters;

        /// <summary>
        /// lblNewStudents24h control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNewStudents24h;

        /// <summary>
        /// lblNewStudentsWeek control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNewStudentsWeek;

        /// <summary>
        /// lblNewStudentsMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNewStudentsMonth;

        /// <summary>
        /// lblBlockedStudents control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblBlockedStudents;

        /// <summary>
        /// lblLevel1Complete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblLevel1Complete;

        /// <summary>
        /// lblLevel2Complete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblLevel2Complete;

        /// <summary>
        /// lblLevel3Complete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblLevel3Complete;

        /// <summary>
        /// lblAvgProgress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAvgProgress;

        /// <summary>
        /// lblFullProgress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFullProgress;

        /// <summary>
        /// lblStudentCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStudentCount;

        /// <summary>
        /// gvStudents control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvStudents;

        /// <summary>
        /// lblNoStudents control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoStudents;

        /// <summary>
        /// lblNewTeachers24h control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNewTeachers24h;

        /// <summary>
        /// lblNewTeachersWeek control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNewTeachersWeek;

        /// <summary>
        /// lblNewTeachersMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNewTeachersMonth;

        /// <summary>
        /// lblTotalClassesCreated control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalClassesCreated;

        /// <summary>
        /// lblTeacherCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTeacherCount;

        /// <summary>
        /// gvTeachers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvTeachers;

        /// <summary>
        /// lblNoTeachers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoTeachers;

        /// <summary>
        /// lblInactiveClasses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblInactiveClasses;

        /// <summary>
        /// lblAvgStudentsPerClass control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAvgStudentsPerClass;

        /// <summary>
        /// lblMostPopularClass control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMostPopularClass;

        /// <summary>
        /// lblClassCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblClassCount;

        /// <summary>
        /// gvClasses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvClasses;

        /// <summary>
        /// lblNoClasses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoClasses;

        /// <summary>
        /// lblPageError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPageError;

        /// <summary>
        /// lblPageMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPageMessage;
    }
}
