//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RookiesInTraining2.Pages.admin
{
    public partial class view_forum_post
    {
        protected global::System.Web.UI.WebControls.Label lblPostTitle;
        protected global::System.Web.UI.WebControls.Label lblAuthor;
        protected global::System.Web.UI.WebControls.Label lblDate;
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
        protected global::System.Web.UI.WebControls.Label lblContent;
        protected global::System.Web.UI.WebControls.Label lblReplyCount;
        protected global::System.Web.UI.WebControls.Repeater rptReplies;
        protected global::System.Web.UI.WebControls.Label lblNoReplies;
        protected global::System.Web.UI.WebControls.Label lblReplyError;
        protected global::System.Web.UI.WebControls.TextBox txtReply;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvReply;
        protected global::System.Web.UI.WebControls.HiddenField hfPostSlug;
        protected global::System.Web.UI.WebControls.HiddenField hfClassSlug;
        protected global::System.Web.UI.WebControls.Button btnPostReply;
    }
}


