//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RookiesInTraining2.Pages
{
    public partial class add_questions
    {
        protected global::System.Web.UI.WebControls.Label lblQuestionError;
        protected global::System.Web.UI.WebControls.TextBox txtQuestionBody;
        protected global::System.Web.UI.WebControls.TextBox txtOption1;
        protected global::System.Web.UI.WebControls.TextBox txtOption2;
        protected global::System.Web.UI.WebControls.TextBox txtOption3;
        protected global::System.Web.UI.WebControls.TextBox txtOption4;
        protected global::System.Web.UI.WebControls.HiddenField hfCorrectAnswerIdx;
        protected global::System.Web.UI.WebControls.TextBox txtExplanation;
        protected global::System.Web.UI.WebControls.DropDownList ddlDifficulty;
        protected global::System.Web.UI.WebControls.Button btnSaveQuestion;
        protected global::System.Web.UI.WebControls.Button btnSaveAndAddAnother;
        
        protected global::System.Web.UI.WebControls.HiddenField hfQuizSlug;
        protected global::System.Web.UI.WebControls.HiddenField hfQuestionsJson;
        protected global::System.Web.UI.WebControls.HiddenField hfQuizData;
    }
}

