//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RookiesInTraining2.Pages.teacher
{
    public partial class edit_level
    {
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Label lblLevelNumber;
        protected global::System.Web.UI.WebControls.TextBox txtLevelTitle;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTitle;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.TextBox txtMinutes;
        protected global::System.Web.UI.WebControls.TextBox txtXP;
        protected global::System.Web.UI.WebControls.CheckBox chkPublished;
        protected global::System.Web.UI.WebControls.FileUpload fileUpload;
        protected global::System.Web.UI.WebControls.Label lblCurrentFile;
        protected global::System.Web.UI.WebControls.HiddenField hfLevelSlug;
        protected global::System.Web.UI.WebControls.HiddenField hfClassSlug;
        protected global::System.Web.UI.WebControls.HyperLink lnkCancel;
        protected global::System.Web.UI.WebControls.Button btnSaveLevel;
    }
}

