//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RookiesInTraining2.Pages.teacher
{
    public partial class edit_question
    {
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
        protected global::System.Web.UI.WebControls.Label lblQuizTitle;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.TextBox txtQuestionBody;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected global::System.Web.UI.WebControls.TextBox txtOption1;
        protected global::System.Web.UI.WebControls.TextBox txtOption2;
        protected global::System.Web.UI.WebControls.TextBox txtOption3;
        protected global::System.Web.UI.WebControls.TextBox txtOption4;
        protected global::System.Web.UI.WebControls.HiddenField hfCorrectAnswerIdx;
        protected global::System.Web.UI.WebControls.TextBox txtExplanation;
        protected global::System.Web.UI.WebControls.DropDownList ddlDifficulty;
        protected global::System.Web.UI.WebControls.Button btnSaveQuestion;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.HiddenField hfQuestionSlug;
        protected global::System.Web.UI.WebControls.HiddenField hfQuizSlug;
        protected global::System.Web.UI.WebControls.HiddenField hfClassSlug;
    }
}






