//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RookiesInTraining2.Pages.teacher
{
    public partial class edit_quiz
    {
        protected global::System.Web.UI.WebControls.Label lblQuizTitle;
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.DropDownList ddlMode;
        protected global::System.Web.UI.WebControls.TextBox txtTimeLimit;
        protected global::System.Web.UI.WebControls.TextBox txtPassingScore;
        protected global::System.Web.UI.WebControls.CheckBox chkPublished;
        protected global::System.Web.UI.WebControls.HiddenField hfQuizSlug;
        protected global::System.Web.UI.WebControls.HiddenField hfLevelSlug;
        protected global::System.Web.UI.WebControls.HiddenField hfClassSlug;
        protected global::System.Web.UI.WebControls.Button btnSaveSettings;
        protected global::System.Web.UI.WebControls.HyperLink lnkAddQuestions;
        protected global::System.Web.UI.WebControls.Repeater rptQuestions;
        protected global::System.Web.UI.WebControls.Label lblNoQuestions;
        protected global::System.Web.UI.WebControls.HyperLink lnkAddFirstQuestion;
    }
}

