//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RookiesInTraining2.Pages.teacher
{
    public partial class manage_classes
    {
        protected global::System.Web.UI.WebControls.Repeater rptClasses;
        protected global::System.Web.UI.WebControls.TextBox txtDeleteConfirm;
        protected global::System.Web.UI.WebControls.Label lblDeleteError;
        protected global::System.Web.UI.WebControls.HiddenField hfDeleteClassSlug;
        protected global::System.Web.UI.WebControls.HiddenField hfDeleteClassName;
        protected global::System.Web.UI.WebControls.Button btnConfirmDelete;
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedClassSlug;
        protected global::System.Web.UI.WebControls.HiddenField hfClassesJson;
        protected global::System.Web.UI.WebControls.HiddenField hfLevelsJson;
        protected global::System.Web.UI.WebControls.HiddenField hfForumPostsJson;
    }
}

