//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RookiesInTraining2.Pages
{
    public partial class teacher_browse_classes
    {
        /// <summary>
        /// hfClassesJson control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfClassesJson;
    }
}

