//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RookiesInTraining2.Pages
{
    public partial class class_detail
    {
        protected global::System.Web.UI.WebControls.Label lblLevelError;
        protected global::System.Web.UI.WebControls.TextBox txtLevelNumber;
        protected global::System.Web.UI.WebControls.TextBox txtLevelTitle;
        protected global::System.Web.UI.WebControls.TextBox txtLevelDescription;
        protected global::System.Web.UI.WebControls.TextBox txtEstimatedMinutes;
        protected global::System.Web.UI.WebControls.TextBox txtXpReward;
        protected global::System.Web.UI.WebControls.FileUpload fileUpload;
        protected global::System.Web.UI.WebControls.CheckBox chkPublishLevel;
        protected global::System.Web.UI.WebControls.Button btnSaveLevel;
        
        protected global::System.Web.UI.WebControls.Label lblQuizError;
        protected global::System.Web.UI.WebControls.DropDownList ddlLevelForQuiz;
        protected global::System.Web.UI.WebControls.TextBox txtQuizTitle;
        protected global::System.Web.UI.WebControls.TextBox txtTimeLimit;
        protected global::System.Web.UI.WebControls.TextBox txtPassingScore;
        protected global::System.Web.UI.WebControls.DropDownList ddlQuizMode;
        protected global::System.Web.UI.WebControls.CheckBox chkPublishQuiz;
        protected global::System.Web.UI.WebControls.Button btnSaveQuiz;
        
        protected global::System.Web.UI.WebControls.HiddenField hfClassSlug;
        protected global::System.Web.UI.WebControls.HiddenField hfLevelsJson;
        protected global::System.Web.UI.WebControls.HiddenField hfStudentsJson;
        protected global::System.Web.UI.WebControls.HiddenField hfQuizzesJson;
        protected global::System.Web.UI.WebControls.HiddenField hfClassData;
    }
}

