//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RookiesInTraining2.Pages
{
    public partial class dashboard_teacher
    {
        /// <summary>
        /// lblTeacherName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTeacherName;

        /// <summary>
        /// lblTodayClasses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTodayClasses;

        /// <summary>
        /// lblCurrentDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCurrentDate;

        /// <summary>
        /// lblMyCourses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMyCourses;

        /// <summary>
        /// lblTotalStudents control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalStudents;

        /// <summary>
        /// lblPendingAssignments control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPendingAssignments;

        /// <summary>
        /// lblMaterials control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMaterials;

        /// <summary>
        /// rptCourses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCourses;

        /// <summary>
        /// lblNoCoursesMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoCoursesMessage;

        /// <summary>
        /// rptActivity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptActivity;

        /// <summary>
        /// lblNoActivityMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoActivityMessage;

        /// <summary>
        /// lblPendingCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPendingCount;

        /// <summary>
        /// rptPendingItems control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptPendingItems;

        /// <summary>
        /// lblNoPendingMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoPendingMessage;
    }
}


