//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RookiesInTraining2.Pages
{
    public partial class teacher_create_class
    {
        /// <summary>
        /// lblError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblError;

        /// <summary>
        /// txtClassName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtClassName;

        /// <summary>
        /// txtClassCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtClassCode;

        /// <summary>
        /// hfSelectedIcon control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedIcon;

        /// <summary>
        /// hfSelectedColor control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedColor;

        /// <summary>
        /// txtDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescription;

        /// <summary>
        /// hfLevelsData control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfLevelsData;

        /// <summary>
        /// btnCreateClass control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCreateClass;
    }
}

