//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RookiesInTraining2.Pages
{
    public partial class teacher_classes
    {
        /// <summary>
        /// lblModalError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblModalError;

        /// <summary>
        /// txtClassName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtClassName;

        /// <summary>
        /// txtClassCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtClassCode;

        /// <summary>
        /// txtDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescription;

        /// <summary>
        /// hfSelectedIcon control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedIcon;

        /// <summary>
        /// hfSelectedColor control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedColor;

        /// <summary>
        /// btnSaveClass control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveClass;

        /// <summary>
        /// Level 1 controls (fixed)
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLevel1Title;
        protected global::System.Web.UI.WebControls.FileUpload fileLevel1;
        protected global::System.Web.UI.WebControls.TextBox txtLevel1Content;

        /// <summary>
        /// Level 2 controls (fixed)
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLevel2Title;
        protected global::System.Web.UI.WebControls.FileUpload fileLevel2;
        protected global::System.Web.UI.WebControls.TextBox txtLevel2Content;

        /// <summary>
        /// Level 3 controls (fixed)
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLevel3Title;
        protected global::System.Web.UI.WebControls.FileUpload fileLevel3;
        protected global::System.Web.UI.WebControls.TextBox txtLevel3Content;

        /// <summary>
        /// hfLevelsData - Stores all levels data as JSON
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfLevelsData;

        /// <summary>
        /// hfClassesJson control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfClassesJson;

        /// <summary>
        /// hfEditingClassSlug control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfEditingClassSlug;
    }
}


